# Generated by Django 5.0.6 on 2024-07-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transacao',
            field=models.CharField(choices=[('Doação', 'Doação'), ('Perda', 'Perda'), ('Transferência', 'Transferência'), ('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=100),
        ),
    ]
