# Generated by Django 5.0.6 on 2024-07-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_transaction_transacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoMovimentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
                ('preco_saida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app.detalheproduto')),
                ('id_produto_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_saida', to='app.detalheproduto')),
            ],
        ),
    ]
