# Generated by Django 5.0.7 on 2024-07-12 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=15)),
                ('marca_produto', models.CharField(max_length=15)),
                ('modelo_produto', models.CharField(max_length=15)),
                ('fabricante', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Details_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_produto', models.CharField(max_length=10)),
                ('sabor_produto', models.CharField(max_length=15)),
                ('tipo_embalagem_produto', models.CharField(max_length=20)),
                ('preco_custo_produto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preco_venda_produto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.product')),
            ],
        ),
    ]
