# Generated by Django 5.0.7 on 2024-07-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_embalagem', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='details_product',
            name='quantidade_produto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details_product',
            name='tipo_embalagem_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging', to='app.packaging_types'),
        ),
    ]
