# Generated by Django 5.0.7 on 2024-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_packaging_types_details_product_quantidade_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_product',
            name='unidade_produto',
            field=models.IntegerField(default=0),
        ),
    ]
