# Generated by Django 5.0.7 on 2024-07-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_details_product_unidade_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='marca_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='app.marca'),
        ),
    ]
