# Generated by Django 5.0.7 on 2024-07-12 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_marca_alter_product_marca_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fabricante', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Instituic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modelo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SectorSuper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_supersetor', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabricante',
        ),
        migrations.AddField(
            model_name='details_product',
            name='quantidade_embalagem_produto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details_product',
            name='tipo_embalagem_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.packaging_types'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marca_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app.marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabricante_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app.fabricante'),
        ),
        migrations.CreateModel(
            name='InstituicUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=8)),
                ('instituic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='app.instituic')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='modelo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app.model'),
        ),
        migrations.CreateModel(
            name='SectorSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subsetor', models.CharField(max_length=20)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsetores', to='app.sector')),
            ],
        ),
        migrations.AddField(
            model_name='sector',
            name='supersetor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='app.sectorsuper'),
        ),
    ]
