# Generated by Django 5.0.6 on 2024-07-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sector'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='SuperSetor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sectorsuper'),
        ),
    ]
