# Generated by Django 5.0.6 on 2024-12-28 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customuser_setor_remove_customuser_supersetor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhess', to='app.detalheproduto')),
            ],
        ),
    ]
