# Generated by Django 5.0.6 on 2024-12-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_detalheprodutoestoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalheproduto',
            name='quantidade_produto',
        ),
    ]
