# Generated by Django 5.0.6 on 2024-12-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_detalheproduto_quantidade_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheProdutoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkCaminho', models.CharField(max_length=100)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_det', to='app.detalheproduto')),
            ],
        ),
    ]
