# Generated by Django 5.0.6 on 2024-12-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_detalheprodutofoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalheproduto',
            name='subsetor',
        ),
        migrations.AddField(
            model_name='detalheprodutoestoque',
            name='id_subsector',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subsetor', to='app.subsector'),
            preserve_default=False,
        ),
    ]
